services:
  netbox:
    ports:
      - "9000:8080"
    environment:
      SKIP_SUPERUSER: "false"
    volumes:
      - /home/docker/Netbox/config:/etc/netbox/config:ro
      - /home/docker/Netbox/media:/opt/netbox/netbox/media:rw
      - /home/docker/Netbox/reports:/opt/netbox/netbox/reports:rw
      - /home/docker/Netbox/scripts:/opt/netbox/netbox/scripts:rw
